# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Main_page.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QStatusBar, QToolBar, QWidget)
import Main_Icons_rc
import Main_Icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1406, 858)
        MainWindow.setMouseTracking(False)
        MainWindow.setTabletTracking(False)
        MainWindow.setAcceptDrops(False)
        MainWindow.setToolButtonStyle(Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.actionOpen_Deleted = QAction(MainWindow)
        self.actionOpen_Deleted.setObjectName(u"actionOpen_Deleted")
        self.actionProfiles = QAction(MainWindow)
        self.actionProfiles.setObjectName(u"actionProfiles")
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName(u"actionClose")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon = QIcon()
        icon.addFile(u":/Main_Window/Icons/Save.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSave.setIcon(icon)
        self.actionSave_as_Picture = QAction(MainWindow)
        self.actionSave_as_Picture.setObjectName(u"actionSave_as_Picture")
        icon1 = QIcon()
        icon1.addFile(u":/Main_Window/Icons/Save_as_image.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSave_as_Picture.setIcon(icon1)
        self.actionOpen_Data_Folder = QAction(MainWindow)
        self.actionOpen_Data_Folder.setObjectName(u"actionOpen_Data_Folder")
        icon2 = QIcon()
        icon2.addFile(u":/Main_Window/Icons/Open_Data_Folder.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOpen_Data_Folder.setIcon(icon2)
        self.actionPrint = QAction(MainWindow)
        self.actionPrint.setObjectName(u"actionPrint")
        icon3 = QIcon()
        icon3.addFile(u":/Main_Window/Icons/Print.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPrint.setIcon(icon3)
        self.actionPrint_Preview = QAction(MainWindow)
        self.actionPrint_Preview.setObjectName(u"actionPrint_Preview")
        icon4 = QIcon()
        icon4.addFile(u":/Main_Window/Icons/Print_Preview.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPrint_Preview.setIcon(icon4)
        self.actionPrint_Setup = QAction(MainWindow)
        self.actionPrint_Setup.setObjectName(u"actionPrint_Setup")
        icon5 = QIcon()
        icon5.addFile(u":/Main_Window/Icons/Print_setup.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPrint_Setup.setIcon(icon5)
        self.actionOpen_an_Account = QAction(MainWindow)
        self.actionOpen_an_Account.setObjectName(u"actionOpen_an_Account")
        icon6 = QIcon()
        icon6.addFile(u":/Main_Window/Icons/Open_an_account.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOpen_an_Account.setIcon(icon6)
        self.actionDeposit = QAction(MainWindow)
        self.actionDeposit.setObjectName(u"actionDeposit")
        icon7 = QIcon()
        icon7.addFile(u":/Main_Window/Icons/Deposit.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionDeposit.setIcon(icon7)
        self.actionWithdrawl = QAction(MainWindow)
        self.actionWithdrawl.setObjectName(u"actionWithdrawl")
        icon8 = QIcon()
        icon8.addFile(u":/Main_Window/Icons/Withdrawal.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionWithdrawl.setIcon(icon8)
        self.actionLogin_to_Trade_Account = QAction(MainWindow)
        self.actionLogin_to_Trade_Account.setObjectName(u"actionLogin_to_Trade_Account")
        icon9 = QIcon()
        icon9.addFile(u":/Main_Window/Icons/Login_to_trade.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionLogin_to_Trade_Account.setIcon(icon9)
        self.actionLogin_to_Webtrader = QAction(MainWindow)
        self.actionLogin_to_Webtrader.setObjectName(u"actionLogin_to_Webtrader")
        icon10 = QIcon()
        icon10.addFile(u":/Main_Window/Icons/Web_trader.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionLogin_to_Webtrader.setIcon(icon10)
        self.actionLogin_to_MQL5_community = QAction(MainWindow)
        self.actionLogin_to_MQL5_community.setObjectName(u"actionLogin_to_MQL5_community")
        icon11 = QIcon()
        icon11.addFile(u":/Main_Window/Icons/Community.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionLogin_to_MQL5_community.setIcon(icon11)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        icon12 = QIcon()
        icon12.addFile(u":/Main_Window/Icons/Exit.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionExit.setIcon(icon12)
        self.actionEURUSD = QAction(MainWindow)
        self.actionEURUSD.setObjectName(u"actionEURUSD")
        self.actionGBPUSD = QAction(MainWindow)
        self.actionGBPUSD.setObjectName(u"actionGBPUSD")
        self.actionUSDCHF = QAction(MainWindow)
        self.actionUSDCHF.setObjectName(u"actionUSDCHF")
        self.actionUSDJPY = QAction(MainWindow)
        self.actionUSDJPY.setObjectName(u"actionUSDJPY")
        self.actionUSDCNH = QAction(MainWindow)
        self.actionUSDCNH.setObjectName(u"actionUSDCNH")
        self.actionAUDUSD = QAction(MainWindow)
        self.actionAUDUSD.setObjectName(u"actionAUDUSD")
        self.actionForex = QAction(MainWindow)
        self.actionForex.setObjectName(u"actionForex")
        self.actionEURUSD_2 = QAction(MainWindow)
        self.actionEURUSD_2.setObjectName(u"actionEURUSD_2")
        self.actionGBPUSD_2 = QAction(MainWindow)
        self.actionGBPUSD_2.setObjectName(u"actionGBPUSD_2")
        self.actionUSDJPY_2 = QAction(MainWindow)
        self.actionUSDJPY_2.setObjectName(u"actionUSDJPY_2")
        self.actionUSDCNH_2 = QAction(MainWindow)
        self.actionUSDCNH_2.setObjectName(u"actionUSDCNH_2")
        self.actionAUDUSD_2 = QAction(MainWindow)
        self.actionAUDUSD_2.setObjectName(u"actionAUDUSD_2")
        self.actionEURUSD_3 = QAction(MainWindow)
        self.actionEURUSD_3.setObjectName(u"actionEURUSD_3")
        self.actionGBPUSD_3 = QAction(MainWindow)
        self.actionGBPUSD_3.setObjectName(u"actionGBPUSD_3")
        self.actionUSDCHF_2 = QAction(MainWindow)
        self.actionUSDCHF_2.setObjectName(u"actionUSDCHF_2")
        self.actionUSDJPY_3 = QAction(MainWindow)
        self.actionUSDJPY_3.setObjectName(u"actionUSDJPY_3")
        self.actionUSDCNH_3 = QAction(MainWindow)
        self.actionUSDCNH_3.setObjectName(u"actionUSDCNH_3")
        self.actionAUDUSD_3 = QAction(MainWindow)
        self.actionAUDUSD_3.setObjectName(u"actionAUDUSD_3")
        self.actionNZDUSD = QAction(MainWindow)
        self.actionNZDUSD.setObjectName(u"actionNZDUSD")
        self.actionUSDCAD = QAction(MainWindow)
        self.actionUSDCAD.setObjectName(u"actionUSDCAD")
        self.actionUSDSEK = QAction(MainWindow)
        self.actionUSDSEK.setObjectName(u"actionUSDSEK")
        self.actionSP500m = QAction(MainWindow)
        self.actionSP500m.setObjectName(u"actionSP500m")
        self.actionAMD = QAction(MainWindow)
        self.actionAMD.setObjectName(u"actionAMD")
        self.actionMSFT = QAction(MainWindow)
        self.actionMSFT.setObjectName(u"actionMSFT")
        self.actionINTC = QAction(MainWindow)
        self.actionINTC.setObjectName(u"actionINTC")
        self.actionNVDA = QAction(MainWindow)
        self.actionNVDA.setObjectName(u"actionNVDA")
        self.actionStatus_Bar = QAction(MainWindow)
        self.actionStatus_Bar.setObjectName(u"actionStatus_Bar")
        self.actionCharts_Bar = QAction(MainWindow)
        self.actionCharts_Bar.setObjectName(u"actionCharts_Bar")
        self.actionSymbols = QAction(MainWindow)
        self.actionSymbols.setObjectName(u"actionSymbols")
        self.actionDepth_Of_Market = QAction(MainWindow)
        self.actionDepth_Of_Market.setObjectName(u"actionDepth_Of_Market")
        self.actionMarket_Watch = QAction(MainWindow)
        self.actionMarket_Watch.setObjectName(u"actionMarket_Watch")
        self.actionData_Window = QAction(MainWindow)
        self.actionData_Window.setObjectName(u"actionData_Window")
        self.actionNavigator = QAction(MainWindow)
        self.actionNavigator.setObjectName(u"actionNavigator")
        self.actionToolbox = QAction(MainWindow)
        self.actionToolbox.setObjectName(u"actionToolbox")
        self.actionStratergy_Tester = QAction(MainWindow)
        self.actionStratergy_Tester.setObjectName(u"actionStratergy_Tester")
        self.actionCharts = QAction(MainWindow)
        self.actionCharts.setObjectName(u"actionCharts")
        self.actionReports = QAction(MainWindow)
        self.actionReports.setObjectName(u"actionReports")
        self.actionFull_Screen = QAction(MainWindow)
        self.actionFull_Screen.setObjectName(u"actionFull_Screen")
        self.actionSystem = QAction(MainWindow)
        self.actionSystem.setObjectName(u"actionSystem")
        self.actionLight = QAction(MainWindow)
        self.actionLight.setObjectName(u"actionLight")
        self.actionDark = QAction(MainWindow)
        self.actionDark.setObjectName(u"actionDark")
        self.actionStandard = QAction(MainWindow)
        self.actionStandard.setObjectName(u"actionStandard")
        self.actionLine_Studies = QAction(MainWindow)
        self.actionLine_Studies.setObjectName(u"actionLine_Studies")
        self.actionTime_Frames = QAction(MainWindow)
        self.actionTime_Frames.setObjectName(u"actionTime_Frames")
        self.actionArabic = QAction(MainWindow)
        self.actionArabic.setObjectName(u"actionArabic")
        self.actionCreate_new_chart = QAction(MainWindow)
        self.actionCreate_new_chart.setObjectName(u"actionCreate_new_chart")
        icon13 = QIcon()
        icon13.addFile(u":/Main_Window/Icons/chart.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCreate_new_chart.setIcon(icon13)
        self.actionmanage_profiles = QAction(MainWindow)
        self.actionmanage_profiles.setObjectName(u"actionmanage_profiles")
        icon14 = QIcon()
        icon14.addFile(u":/Main_Window/Icons/manage_profiles.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionmanage_profiles.setIcon(icon14)
        self.actionshow_symbol_list = QAction(MainWindow)
        self.actionshow_symbol_list.setObjectName(u"actionshow_symbol_list")
        self.actionshow_symbol_list.setCheckable(True)
        icon15 = QIcon()
        icon15.addFile(u":/Main_Window/Icons/show_symbol.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.actionshow_symbol_list.setIcon(icon15)
        self.actionmeta_quote_languages = QAction(MainWindow)
        self.actionmeta_quote_languages.setObjectName(u"actionmeta_quote_languages")
        icon16 = QIcon()
        icon16.addFile(u":/Main_Window/Icons/language_editor.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.actionmeta_quote_languages.setIcon(icon16)
        self.actionOpen_MQL_5_Market = QAction(MainWindow)
        self.actionOpen_MQL_5_Market.setObjectName(u"actionOpen_MQL_5_Market")
        icon17 = QIcon()
        icon17.addFile(u":/Main_Window/Icons/market.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.actionOpen_MQL_5_Market.setIcon(icon17)
        self.actionOpen_MQL5_Signal = QAction(MainWindow)
        self.actionOpen_MQL5_Signal.setObjectName(u"actionOpen_MQL5_Signal")
        icon18 = QIcon()
        icon18.addFile(u":/Main_Window/Icons/signals.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOpen_MQL5_Signal.setIcon(icon18)
        self.actionVirtual_Hosting = QAction(MainWindow)
        self.actionVirtual_Hosting.setObjectName(u"actionVirtual_Hosting")
        icon19 = QIcon()
        icon19.addFile(u":/Main_Window/Icons/virtual_hosting.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionVirtual_Hosting.setIcon(icon19)
        self.actionRegister_Account_to_trade = QAction(MainWindow)
        self.actionRegister_Account_to_trade.setObjectName(u"actionRegister_Account_to_trade")
        icon20 = QIcon()
        icon20.addFile(u":/Main_Window/Icons/register_account.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRegister_Account_to_trade.setIcon(icon20)
        self.actionalgo_trading = QAction(MainWindow)
        self.actionalgo_trading.setObjectName(u"actionalgo_trading")
        icon21 = QIcon()
        icon21.addFile(u":/Main_Window/Icons/allow_or_prohibit_trading.png", QSize(), QIcon.Mode.Selected, QIcon.State.On)
        self.actionalgo_trading.setIcon(icon21)
        self.actionNew_Order = QAction(MainWindow)
        self.actionNew_Order.setObjectName(u"actionNew_Order")
        icon22 = QIcon()
        icon22.addFile(u":/Main_Window/Icons/new_order.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionNew_Order.setIcon(icon22)
        self.actionBar_Chart = QAction(MainWindow)
        self.actionBar_Chart.setObjectName(u"actionBar_Chart")
        icon23 = QIcon()
        icon23.addFile(u":/Main_Window/Icons/bar_chart.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionBar_Chart.setIcon(icon23)
        self.actionCandle_Chart = QAction(MainWindow)
        self.actionCandle_Chart.setObjectName(u"actionCandle_Chart")
        icon24 = QIcon()
        icon24.addFile(u":/Main_Window/Icons/candle_chart.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCandle_Chart.setIcon(icon24)
        self.actionLine_Chart = QAction(MainWindow)
        self.actionLine_Chart.setObjectName(u"actionLine_Chart")
        icon25 = QIcon()
        icon25.addFile(u":/Main_Window/Icons/line_chart.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionLine_Chart.setIcon(icon25)
        self.actionZoom_in = QAction(MainWindow)
        self.actionZoom_in.setObjectName(u"actionZoom_in")
        icon26 = QIcon()
        icon26.addFile(u":/Main_Window/Icons/zoom_in.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionZoom_in.setIcon(icon26)
        self.actionZoom_Out = QAction(MainWindow)
        self.actionZoom_Out.setObjectName(u"actionZoom_Out")
        icon27 = QIcon()
        icon27.addFile(u":/Main_Window/Icons/zoom_out.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionZoom_Out.setIcon(icon27)
        self.actionArrange_windows_as_non_overlpping_Style = QAction(MainWindow)
        self.actionArrange_windows_as_non_overlpping_Style.setObjectName(u"actionArrange_windows_as_non_overlpping_Style")
        icon28 = QIcon()
        icon28.addFile(u":/Main_Window/Icons/arrange_windows.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionArrange_windows_as_non_overlpping_Style.setIcon(icon28)
        self.actionmove_to_end_of_chart = QAction(MainWindow)
        self.actionmove_to_end_of_chart.setObjectName(u"actionmove_to_end_of_chart")
        icon29 = QIcon()
        icon29.addFile(u":/Main_Window/Icons/move_to_end_of_chart.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionmove_to_end_of_chart.setIcon(icon29)
        self.actionshift_end_of_chart_from_right_border = QAction(MainWindow)
        self.actionshift_end_of_chart_from_right_border.setObjectName(u"actionshift_end_of_chart_from_right_border")
        icon30 = QIcon()
        icon30.addFile(u":/Main_Window/Icons/shift_end_of_chart_from_right_border.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionshift_end_of_chart_from_right_border.setIcon(icon30)
        self.actionsave_active_chart_as_screenshot = QAction(MainWindow)
        self.actionsave_active_chart_as_screenshot.setObjectName(u"actionsave_active_chart_as_screenshot")
        icon31 = QIcon()
        icon31.addFile(u":/Main_Window/Icons/save_active_chart.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionsave_active_chart_as_screenshot.setIcon(icon31)
        self.actioncursor = QAction(MainWindow)
        self.actioncursor.setObjectName(u"actioncursor")
        icon32 = QIcon()
        icon32.addFile(u":/Main_Window/Icons/cursor.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actioncursor.setIcon(icon32)
        self.actioncrosshair = QAction(MainWindow)
        self.actioncrosshair.setObjectName(u"actioncrosshair")
        icon33 = QIcon()
        icon33.addFile(u":/Main_Window/Icons/cross_hair.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actioncrosshair.setIcon(icon33)
        self.actiondraw_vertical_line = QAction(MainWindow)
        self.actiondraw_vertical_line.setObjectName(u"actiondraw_vertical_line")
        icon34 = QIcon()
        icon34.addFile(u":/Main_Window/Icons/vertical_line.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actiondraw_vertical_line.setIcon(icon34)
        self.actiondraw_horizantal_line = QAction(MainWindow)
        self.actiondraw_horizantal_line.setObjectName(u"actiondraw_horizantal_line")
        icon35 = QIcon()
        icon35.addFile(u":/Main_Window/Icons/horizantal_line.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actiondraw_horizantal_line.setIcon(icon35)
        self.actiondraw_trend_line = QAction(MainWindow)
        self.actiondraw_trend_line.setObjectName(u"actiondraw_trend_line")
        icon36 = QIcon()
        icon36.addFile(u":/Main_Window/Icons/trend_line.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actiondraw_trend_line.setIcon(icon36)
        self.actiondraw_fibonacci_pattern = QAction(MainWindow)
        self.actiondraw_fibonacci_pattern.setObjectName(u"actiondraw_fibonacci_pattern")
        icon37 = QIcon()
        icon37.addFile(u":/Main_Window/Icons/pattern.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actiondraw_fibonacci_pattern.setIcon(icon37)
        self.actionText = QAction(MainWindow)
        self.actionText.setObjectName(u"actionText")
        icon38 = QIcon()
        icon38.addFile(u":/Main_Window/Icons/text.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionText.setIcon(icon38)
        self.actiondraw_arrow = QAction(MainWindow)
        self.actiondraw_arrow.setObjectName(u"actiondraw_arrow")
        icon39 = QIcon()
        icon39.addFile(u":/Main_Window/Icons/draw_shapes.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actiondraw_arrow.setIcon(icon39)
        self.actiondraw_equidistant = QAction(MainWindow)
        self.actiondraw_equidistant.setObjectName(u"actiondraw_equidistant")
        icon40 = QIcon()
        icon40.addFile(u":/Main_Window/Icons/equidistant_channel.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actiondraw_equidistant.setIcon(icon40)
        self.action1_Minute = QAction(MainWindow)
        self.action1_Minute.setObjectName(u"action1_Minute")
        icon41 = QIcon()
        icon41.addFile(u":/Main_Window/Icons/time.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action1_Minute.setIcon(icon41)
        self.actionsearch = QAction(MainWindow)
        self.actionsearch.setObjectName(u"actionsearch")
        icon42 = QIcon()
        icon42.addFile(u":/Main_Window/Icons/search.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionsearch.setIcon(icon42)
        self.actionMQL5_Community = QAction(MainWindow)
        self.actionMQL5_Community.setObjectName(u"actionMQL5_Community")
        icon43 = QIcon()
        icon43.addFile(u":/Main_Window/Icons/community.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionMQL5_Community.setIcon(icon43)
        self.actionLevel = QAction(MainWindow)
        self.actionLevel.setObjectName(u"actionLevel")
        icon44 = QIcon()
        icon44.addFile(u":/Main_Window/Icons/achievment.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionLevel.setIcon(icon44)
        self.actionIndicators = QAction(MainWindow)
        self.actionIndicators.setObjectName(u"actionIndicators")
        self.actionObjects = QAction(MainWindow)
        self.actionObjects.setObjectName(u"actionObjects")
        self.actionExperts = QAction(MainWindow)
        self.actionExperts.setObjectName(u"actionExperts")
        self.actionScripts = QAction(MainWindow)
        self.actionScripts.setObjectName(u"actionScripts")
        self.actionDepth_of_Market = QAction(MainWindow)
        self.actionDepth_of_Market.setObjectName(u"actionDepth_of_Market")
        self.actionIndicators_List = QAction(MainWindow)
        self.actionIndicators_List.setObjectName(u"actionIndicators_List")
        self.actionObjects_2 = QAction(MainWindow)
        self.actionObjects_2.setObjectName(u"actionObjects_2")
        self.actionExperts_List = QAction(MainWindow)
        self.actionExperts_List.setObjectName(u"actionExperts_List")
        self.actionBar_Chart_2 = QAction(MainWindow)
        self.actionBar_Chart_2.setObjectName(u"actionBar_Chart_2")
        self.actionCandle_Stick = QAction(MainWindow)
        self.actionCandle_Stick.setObjectName(u"actionCandle_Stick")
        self.actionLine_Chart_2 = QAction(MainWindow)
        self.actionLine_Chart_2.setObjectName(u"actionLine_Chart_2")
        self.actionTime_Frames_2 = QAction(MainWindow)
        self.actionTime_Frames_2.setObjectName(u"actionTime_Frames_2")
        self.actionTemplates = QAction(MainWindow)
        self.actionTemplates.setObjectName(u"actionTemplates")
        self.actionGrid = QAction(MainWindow)
        self.actionGrid.setObjectName(u"actionGrid")
        self.actionAuto_Scroll = QAction(MainWindow)
        self.actionAuto_Scroll.setObjectName(u"actionAuto_Scroll")
        self.actionCharts_shift = QAction(MainWindow)
        self.actionCharts_shift.setObjectName(u"actionCharts_shift")
        self.actionVolumes = QAction(MainWindow)
        self.actionVolumes.setObjectName(u"actionVolumes")
        self.actionTick_Volumes = QAction(MainWindow)
        self.actionTick_Volumes.setObjectName(u"actionTick_Volumes")
        self.actionTrade_Levels = QAction(MainWindow)
        self.actionTrade_Levels.setObjectName(u"actionTrade_Levels")
        self.actionTrade_History = QAction(MainWindow)
        self.actionTrade_History.setObjectName(u"actionTrade_History")
        self.actionZomm_In = QAction(MainWindow)
        self.actionZomm_In.setObjectName(u"actionZomm_In")
        self.actionZoom_out = QAction(MainWindow)
        self.actionZoom_out.setObjectName(u"actionZoom_out")
        self.actionstep_by_step = QAction(MainWindow)
        self.actionstep_by_step.setObjectName(u"actionstep_by_step")
        self.actionProperties = QAction(MainWindow)
        self.actionProperties.setObjectName(u"actionProperties")
        self.actionNew_Order_2 = QAction(MainWindow)
        self.actionNew_Order_2.setObjectName(u"actionNew_Order_2")
        self.actionStratergy_Tester_Agents_management = QAction(MainWindow)
        self.actionStratergy_Tester_Agents_management.setObjectName(u"actionStratergy_Tester_Agents_management")
        self.actionMetaQuote_Language_Editor = QAction(MainWindow)
        self.actionMetaQuote_Language_Editor.setObjectName(u"actionMetaQuote_Language_Editor")
        self.actionTask_Manager = QAction(MainWindow)
        self.actionTask_Manager.setObjectName(u"actionTask_Manager")
        self.actionGlobal_Variables = QAction(MainWindow)
        self.actionGlobal_Variables.setObjectName(u"actionGlobal_Variables")
        self.actionMQL5_market = QAction(MainWindow)
        self.actionMQL5_market.setObjectName(u"actionMQL5_market")
        self.actionMQL5_signals = QAction(MainWindow)
        self.actionMQL5_signals.setObjectName(u"actionMQL5_signals")
        self.actionMQL5_Virtual_Hosting = QAction(MainWindow)
        self.actionMQL5_Virtual_Hosting.setObjectName(u"actionMQL5_Virtual_Hosting")
        self.actionOptions = QAction(MainWindow)
        self.actionOptions.setObjectName(u"actionOptions")
        self.actionTile_Windows = QAction(MainWindow)
        self.actionTile_Windows.setObjectName(u"actionTile_Windows")
        self.actionCascade = QAction(MainWindow)
        self.actionCascade.setObjectName(u"actionCascade")
        self.actionTile_Horizantally = QAction(MainWindow)
        self.actionTile_Horizantally.setObjectName(u"actionTile_Horizantally")
        self.actionTile_Verically = QAction(MainWindow)
        self.actionTile_Verically.setObjectName(u"actionTile_Verically")
        self.actionArrange_Icons = QAction(MainWindow)
        self.actionArrange_Icons.setObjectName(u"actionArrange_Icons")
        self.actionReset_to_Default = QAction(MainWindow)
        self.actionReset_to_Default.setObjectName(u"actionReset_to_Default")
        self.actionResolution = QAction(MainWindow)
        self.actionResolution.setObjectName(u"actionResolution")
        self.actionHelp_Topic_s = QAction(MainWindow)
        self.actionHelp_Topic_s.setObjectName(u"actionHelp_Topic_s")
        self.actionWhat_s_New = QAction(MainWindow)
        self.actionWhat_s_New.setObjectName(u"actionWhat_s_New")
        self.actionMQL5_Telegram_channel = QAction(MainWindow)
        self.actionMQL5_Telegram_channel.setObjectName(u"actionMQL5_Telegram_channel")
        self.actionVideo_Guides = QAction(MainWindow)
        self.actionVideo_Guides.setObjectName(u"actionVideo_Guides")
        self.actionMQL5_Webtrader = QAction(MainWindow)
        self.actionMQL5_Webtrader.setObjectName(u"actionMQL5_Webtrader")
        self.actionMQL5_Docummentation = QAction(MainWindow)
        self.actionMQL5_Docummentation.setObjectName(u"actionMQL5_Docummentation")
        
        # spacer = QWidget()
       # spacer.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
       # spacer.setObjectName(u"spacer")


        self.actiontheme = QAction(MainWindow)
        self.actiontheme.setObjectName(u"actiontheme")


        icon45 = QIcon()
        icon45.addFile(u":/Main_Window/Icons/WhatsApp Image 2026-02-19 at 10.15.23 AM.jpeg", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.actiontheme.setIcon(icon45)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1406, 26))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuNew_Chart = QMenu(self.menuFile)
        self.menuNew_Chart.setObjectName(u"menuNew_Chart")
        self.menuNew_Chart.setToolTipsVisible(False)
        self.menuForex = QMenu(self.menuNew_Chart)
        self.menuForex.setObjectName(u"menuForex")
        self.menuIndexes = QMenu(self.menuNew_Chart)
        self.menuIndexes.setObjectName(u"menuIndexes")
        self.menuNasdaq = QMenu(self.menuNew_Chart)
        self.menuNasdaq.setObjectName(u"menuNasdaq")
        self.menuStock = QMenu(self.menuNasdaq)
        self.menuStock.setObjectName(u"menuStock")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuColors = QMenu(self.menuView)
        self.menuColors.setObjectName(u"menuColors")
        self.menuToolbars = QMenu(self.menuView)
        self.menuToolbars.setObjectName(u"menuToolbars")
        self.menuLanguages = QMenu(self.menuView)
        self.menuLanguages.setObjectName(u"menuLanguages")
        self.menuInsert = QMenu(self.menubar)
        self.menuInsert.setObjectName(u"menuInsert")
        self.menuCharts = QMenu(self.menubar)
        self.menuCharts.setObjectName(u"menuCharts")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuWindows = QMenu(self.menubar)
        self.menuWindows.setObjectName(u"menuWindows")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setAcceptDrops(True)
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuInsert.menuAction())
        self.menubar.addAction(self.menuCharts.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuWindows.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.menuNew_Chart.menuAction())
        self.menuFile.addAction(self.actionOpen_Deleted)
        self.menuFile.addAction(self.actionProfiles)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as_Picture)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_Data_Folder)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionPrint_Preview)
        self.menuFile.addAction(self.actionPrint_Setup)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_an_Account)
        self.menuFile.addAction(self.actionDeposit)
        self.menuFile.addAction(self.actionWithdrawl)
        self.menuFile.addAction(self.actionLogin_to_Trade_Account)
        self.menuFile.addAction(self.actionLogin_to_Webtrader)
        self.menuFile.addAction(self.actionLogin_to_MQL5_community)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addSeparator()
        self.menuFile.addSeparator()
        self.menuNew_Chart.addAction(self.actionEURUSD_2)
        self.menuNew_Chart.addAction(self.actionGBPUSD_2)
        self.menuNew_Chart.addAction(self.actionUSDJPY_2)
        self.menuNew_Chart.addAction(self.actionUSDCNH_2)
        self.menuNew_Chart.addAction(self.actionAUDUSD_2)
        self.menuNew_Chart.addSeparator()
        self.menuNew_Chart.addAction(self.menuForex.menuAction())
        self.menuNew_Chart.addAction(self.menuIndexes.menuAction())
        self.menuNew_Chart.addAction(self.menuNasdaq.menuAction())
        self.menuForex.addAction(self.actionEURUSD_3)
        self.menuForex.addAction(self.actionGBPUSD_3)
        self.menuForex.addAction(self.actionUSDCHF_2)
        self.menuForex.addAction(self.actionUSDJPY_3)
        self.menuForex.addAction(self.actionUSDCNH_3)
        self.menuForex.addAction(self.actionAUDUSD_3)
        self.menuForex.addAction(self.actionNZDUSD)
        self.menuForex.addAction(self.actionUSDCAD)
        self.menuForex.addAction(self.actionUSDSEK)
        self.menuIndexes.addAction(self.actionSP500m)
        self.menuNasdaq.addAction(self.menuStock.menuAction())
        self.menuStock.addAction(self.actionAMD)
        self.menuStock.addAction(self.actionMSFT)
        self.menuStock.addAction(self.actionINTC)
        self.menuStock.addAction(self.actionNVDA)
        self.menuView.addAction(self.menuLanguages.menuAction())
        self.menuView.addAction(self.menuColors.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuToolbars.menuAction())
        self.menuView.addAction(self.actionStatus_Bar)
        self.menuView.addAction(self.actionCharts_Bar)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionSymbols)
        self.menuView.addAction(self.actionDepth_Of_Market)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionMarket_Watch)
        self.menuView.addAction(self.actionData_Window)
        self.menuView.addAction(self.actionNavigator)
        self.menuView.addAction(self.actionToolbox)
        self.menuView.addAction(self.actionStratergy_Tester)
        self.menuView.addAction(self.actionCharts)
        self.menuView.addAction(self.actionReports)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionFull_Screen)
        self.menuColors.addAction(self.actionSystem)
        self.menuColors.addAction(self.actionLight)
        self.menuColors.addAction(self.actionDark)
        self.menuToolbars.addAction(self.actionStandard)
        self.menuToolbars.addAction(self.actionLine_Studies)
        self.menuToolbars.addAction(self.actionTime_Frames)
        self.menuLanguages.addAction(self.actionArabic)
        self.menuInsert.addAction(self.actionIndicators)
        self.menuInsert.addAction(self.actionObjects)
        self.menuInsert.addAction(self.actionExperts)
        self.menuInsert.addAction(self.actionScripts)
        self.menuCharts.addAction(self.actionDepth_of_Market)
        self.menuCharts.addAction(self.actionIndicators_List)
        self.menuCharts.addAction(self.actionObjects_2)
        self.menuCharts.addAction(self.actionExperts_List)
        self.menuCharts.addSeparator()
        self.menuCharts.addAction(self.actionBar_Chart_2)
        self.menuCharts.addAction(self.actionCandle_Stick)
        self.menuCharts.addAction(self.actionLine_Chart_2)
        self.menuCharts.addSeparator()
        self.menuCharts.addAction(self.actionTime_Frames_2)
        self.menuCharts.addAction(self.actionTemplates)
        self.menuCharts.addAction(self.actionGrid)
        self.menuCharts.addAction(self.actionAuto_Scroll)
        self.menuCharts.addAction(self.actionCharts_shift)
        self.menuCharts.addSeparator()
        self.menuCharts.addAction(self.actionVolumes)
        self.menuCharts.addAction(self.actionTick_Volumes)
        self.menuCharts.addAction(self.actionTrade_Levels)
        self.menuCharts.addAction(self.actionTrade_History)
        self.menuCharts.addSeparator()
        self.menuCharts.addAction(self.actionZomm_In)
        self.menuCharts.addAction(self.actionZoom_out)
        self.menuCharts.addAction(self.actionstep_by_step)
        self.menuCharts.addSeparator()
        self.menuCharts.addAction(self.actionProperties)
        self.menuTools.addAction(self.actionNew_Order_2)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionStratergy_Tester_Agents_management)
        self.menuTools.addAction(self.actionMetaQuote_Language_Editor)
        self.menuTools.addAction(self.actionTask_Manager)
        self.menuTools.addAction(self.actionGlobal_Variables)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionMQL5_market)
        self.menuTools.addAction(self.actionMQL5_signals)
        self.menuTools.addAction(self.actionMQL5_Virtual_Hosting)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionOptions)
        self.menuWindows.addAction(self.actionTile_Windows)
        self.menuWindows.addSeparator()
        self.menuWindows.addAction(self.actionCascade)
        self.menuWindows.addAction(self.actionTile_Horizantally)
        self.menuWindows.addAction(self.actionTile_Verically)
        self.menuWindows.addAction(self.actionArrange_Icons)
        self.menuWindows.addAction(self.actionReset_to_Default)
        self.menuWindows.addSeparator()
        self.menuWindows.addAction(self.actionResolution)
        self.menuWindows.addSeparator()
        self.menuHelp.addAction(self.actionHelp_Topic_s)
        self.menuHelp.addAction(self.actionWhat_s_New)
        self.menuHelp.addAction(self.actionMQL5_Telegram_channel)
        self.menuHelp.addAction(self.actionVideo_Guides)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionMQL5_Webtrader)
        self.menuHelp.addAction(self.actionMQL5_Docummentation)
        self.toolBar.addAction(self.actionCreate_new_chart)
        self.toolBar.addAction(self.actionmanage_profiles)
        self.toolBar.addAction(self.actionshow_symbol_list)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionmeta_quote_languages)
        self.toolBar.addAction(self.actionOpen_MQL_5_Market)
        self.toolBar.addAction(self.actionOpen_MQL5_Signal)
        self.toolBar.addAction(self.actionVirtual_Hosting)
        self.toolBar.addAction(self.actionRegister_Account_to_trade)
        self.toolBar.addAction(self.actionalgo_trading)
        self.toolBar.addAction(self.actionNew_Order)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionBar_Chart)
        self.toolBar.addAction(self.actionCandle_Chart)
        self.toolBar.addAction(self.actionLine_Chart)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionZoom_in)
        self.toolBar.addAction(self.actionZoom_Out)
        self.toolBar.addAction(self.actionArrange_windows_as_non_overlpping_Style)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionmove_to_end_of_chart)
        self.toolBar.addAction(self.actionshift_end_of_chart_from_right_border)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionsave_active_chart_as_screenshot)
        self.toolBar.addAction(self.actioncursor)
        self.toolBar.addAction(self.actioncrosshair)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actiondraw_vertical_line)
        self.toolBar.addAction(self.actiondraw_horizantal_line)
        self.toolBar.addAction(self.actiondraw_trend_line)
        self.toolBar.addAction(self.actiondraw_equidistant)
        self.toolBar.addAction(self.actiondraw_fibonacci_pattern)
        self.toolBar.addAction(self.actionText)
        self.toolBar.addAction(self.actiondraw_arrow)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action1_Minute)
        self.toolBar.addAction(self.actionsearch)
        self.toolBar.addAction(self.actionMQL5_Community)
        self.toolBar.addAction(self.actionLevel)
        # Spacer
        spacer = QWidget()
        spacer.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        self.toolBar.addWidget(spacer)
        self.toolBar.addSeparator()

        # Ye action right side chale jayega

        self.toolBar.addAction(self.actiontheme)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"JetFyx", None))
        self.actionOpen_Deleted.setText(QCoreApplication.translate("MainWindow", u"Open Deleted", None))
        self.actionProfiles.setText(QCoreApplication.translate("MainWindow", u"Profiles", None))
        self.actionClose.setText(QCoreApplication.translate("MainWindow", u"Close", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionSave_as_Picture.setText(QCoreApplication.translate("MainWindow", u"Save as Picture", None))
        self.actionOpen_Data_Folder.setText(QCoreApplication.translate("MainWindow", u"Open Data Folder", None))
        self.actionPrint.setText(QCoreApplication.translate("MainWindow", u"Print", None))
        self.actionPrint_Preview.setText(QCoreApplication.translate("MainWindow", u"Print Preview", None))
        self.actionPrint_Setup.setText(QCoreApplication.translate("MainWindow", u"Print Setup", None))
        self.actionOpen_an_Account.setText(QCoreApplication.translate("MainWindow", u"Open an Account", None))
        self.actionDeposit.setText(QCoreApplication.translate("MainWindow", u"Deposit", None))
        self.actionWithdrawl.setText(QCoreApplication.translate("MainWindow", u"Withdrawl", None))
        self.actionLogin_to_Trade_Account.setText(QCoreApplication.translate("MainWindow", u"Login to Trade Account", None))
        self.actionLogin_to_Webtrader.setText(QCoreApplication.translate("MainWindow", u"Login to Web Trader", None))
        self.actionLogin_to_MQL5_community.setText(QCoreApplication.translate("MainWindow", u"Login to MQL5.community", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionEURUSD.setText(QCoreApplication.translate("MainWindow", u"EURUSD", None))
        self.actionGBPUSD.setText(QCoreApplication.translate("MainWindow", u"GBPUSD", None))
        self.actionUSDCHF.setText(QCoreApplication.translate("MainWindow", u"USDCHF", None))
        self.actionUSDJPY.setText(QCoreApplication.translate("MainWindow", u"USDJPY", None))
        self.actionUSDCNH.setText(QCoreApplication.translate("MainWindow", u"USDCNH", None))
        self.actionAUDUSD.setText(QCoreApplication.translate("MainWindow", u"AUDUSD", None))
        self.actionForex.setText(QCoreApplication.translate("MainWindow", u"Forex", None))
        self.actionEURUSD_2.setText(QCoreApplication.translate("MainWindow", u"EURUSD", None))
        self.actionGBPUSD_2.setText(QCoreApplication.translate("MainWindow", u"GBPUSD", None))
        self.actionUSDJPY_2.setText(QCoreApplication.translate("MainWindow", u"USDJPY", None))
        self.actionUSDCNH_2.setText(QCoreApplication.translate("MainWindow", u"USDCNH", None))
        self.actionAUDUSD_2.setText(QCoreApplication.translate("MainWindow", u"AUDUSD", None))
        self.actionEURUSD_3.setText(QCoreApplication.translate("MainWindow", u"EURUSD", None))
        self.actionGBPUSD_3.setText(QCoreApplication.translate("MainWindow", u"GBPUSD", None))
        self.actionUSDCHF_2.setText(QCoreApplication.translate("MainWindow", u"USDCHF", None))
        self.actionUSDJPY_3.setText(QCoreApplication.translate("MainWindow", u"USDJPY", None))
        self.actionUSDCNH_3.setText(QCoreApplication.translate("MainWindow", u"USDCNH", None))
        self.actionAUDUSD_3.setText(QCoreApplication.translate("MainWindow", u"AUDUSD", None))
        self.actionNZDUSD.setText(QCoreApplication.translate("MainWindow", u"NZDUSD", None))
        self.actionUSDCAD.setText(QCoreApplication.translate("MainWindow", u"USDCAD", None))
        self.actionUSDSEK.setText(QCoreApplication.translate("MainWindow", u"USDSEK", None))
        self.actionSP500m.setText(QCoreApplication.translate("MainWindow", u"SP500m", None))
        self.actionAMD.setText(QCoreApplication.translate("MainWindow", u"AMD", None))
        self.actionMSFT.setText(QCoreApplication.translate("MainWindow", u"MSFT", None))
        self.actionINTC.setText(QCoreApplication.translate("MainWindow", u"INTC", None))
        self.actionNVDA.setText(QCoreApplication.translate("MainWindow", u"NVDA", None))
        self.actionStatus_Bar.setText(QCoreApplication.translate("MainWindow", u"Status Bar", None))
        self.actionCharts_Bar.setText(QCoreApplication.translate("MainWindow", u"Charts Bar", None))
        self.actionSymbols.setText(QCoreApplication.translate("MainWindow", u"Symbols", None))
        self.actionDepth_Of_Market.setText(QCoreApplication.translate("MainWindow", u"Depth Of Market", None))
        self.actionMarket_Watch.setText(QCoreApplication.translate("MainWindow", u"Market Watch", None))
        self.actionData_Window.setText(QCoreApplication.translate("MainWindow", u"Data Window", None))
        self.actionNavigator.setText(QCoreApplication.translate("MainWindow", u"Navigator", None))
        self.actionToolbox.setText(QCoreApplication.translate("MainWindow", u"Toolbox", None))
        self.actionStratergy_Tester.setText(QCoreApplication.translate("MainWindow", u"Stratergy Tester", None))
        self.actionCharts.setText(QCoreApplication.translate("MainWindow", u"Charts", None))
        self.actionReports.setText(QCoreApplication.translate("MainWindow", u"Reports", None))
        self.actionFull_Screen.setText(QCoreApplication.translate("MainWindow", u"Full Screen", None))
        self.actionSystem.setText(QCoreApplication.translate("MainWindow", u"System", None))
        self.actionLight.setText(QCoreApplication.translate("MainWindow", u"Light", None))
        self.actionDark.setText(QCoreApplication.translate("MainWindow", u"Dark", None))
        self.actionStandard.setText(QCoreApplication.translate("MainWindow", u"Standard", None))
        self.actionLine_Studies.setText(QCoreApplication.translate("MainWindow", u"Line Studies", None))
        self.actionTime_Frames.setText(QCoreApplication.translate("MainWindow", u"Time Frames", None))
        self.actionArabic.setText(QCoreApplication.translate("MainWindow", u"Arabic", None))
        self.actionCreate_new_chart.setText(QCoreApplication.translate("MainWindow", u"Create new chart", None))
        self.actionmanage_profiles.setText(QCoreApplication.translate("MainWindow", u"manage profiles", None))
        self.actionshow_symbol_list.setText(QCoreApplication.translate("MainWindow", u"show symbol list", None))
#if QT_CONFIG(shortcut)
        self.actionshow_symbol_list.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+U", None))
#endif // QT_CONFIG(shortcut)
        self.actionmeta_quote_languages.setText(QCoreApplication.translate("MainWindow", u"meta quote languages", None))
        self.actionOpen_MQL_5_Market.setText(QCoreApplication.translate("MainWindow", u"Open MQL 5 Market", None))
        self.actionOpen_MQL5_Signal.setText(QCoreApplication.translate("MainWindow", u"Open MQL5 Signal", None))
        self.actionVirtual_Hosting.setText(QCoreApplication.translate("MainWindow", u"Virtual Hosting", None))
        self.actionRegister_Account_to_trade.setText(QCoreApplication.translate("MainWindow", u"Register Account to trade", None))
        self.actionalgo_trading.setText(QCoreApplication.translate("MainWindow", u"algo trading", None))
        self.actionNew_Order.setText(QCoreApplication.translate("MainWindow", u"New Order", None))
        self.actionBar_Chart.setText(QCoreApplication.translate("MainWindow", u"Bar Chart", None))
        self.actionCandle_Chart.setText(QCoreApplication.translate("MainWindow", u"Candle Chart", None))
        self.actionLine_Chart.setText(QCoreApplication.translate("MainWindow", u"Line Chart", None))
        self.actionZoom_in.setText(QCoreApplication.translate("MainWindow", u"Zoom in", None))
        self.actionZoom_Out.setText(QCoreApplication.translate("MainWindow", u"Zoom Out", None))
        self.actionArrange_windows_as_non_overlpping_Style.setText(QCoreApplication.translate("MainWindow", u"Arrange windows as non overlpping Style", None))
#if QT_CONFIG(shortcut)
        self.actionArrange_windows_as_non_overlpping_Style.setShortcut(QCoreApplication.translate("MainWindow", u"Alt+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionmove_to_end_of_chart.setText(QCoreApplication.translate("MainWindow", u"move to end of chart", None))
        self.actionshift_end_of_chart_from_right_border.setText(QCoreApplication.translate("MainWindow", u"shift end of chart from right border", None))
        self.actionsave_active_chart_as_screenshot.setText(QCoreApplication.translate("MainWindow", u"save active chart as screenshot", None))
        self.actioncursor.setText(QCoreApplication.translate("MainWindow", u"cursor", None))
        self.actioncrosshair.setText(QCoreApplication.translate("MainWindow", u"crosshair", None))
        self.actiondraw_vertical_line.setText(QCoreApplication.translate("MainWindow", u"draw vertical line", None))
        self.actiondraw_horizantal_line.setText(QCoreApplication.translate("MainWindow", u"draw horizantal line", None))
        self.actiondraw_trend_line.setText(QCoreApplication.translate("MainWindow", u"draw trend line", None))
        self.actiondraw_fibonacci_pattern.setText(QCoreApplication.translate("MainWindow", u"draw fibonacci pattern", None))
        self.actionText.setText(QCoreApplication.translate("MainWindow", u"Text", None))
        self.actiondraw_arrow.setText(QCoreApplication.translate("MainWindow", u"draw arrow", None))
        self.actiondraw_equidistant.setText(QCoreApplication.translate("MainWindow", u"draw equidistant", None))
        self.action1_Minute.setText(QCoreApplication.translate("MainWindow", u"1 Minute", None))
        self.actionsearch.setText(QCoreApplication.translate("MainWindow", u"search", None))
        self.actionMQL5_Community.setText(QCoreApplication.translate("MainWindow", u"MQL5.Community", None))
        self.actionLevel.setText(QCoreApplication.translate("MainWindow", u"Level", None))
        self.actionIndicators.setText(QCoreApplication.translate("MainWindow", u"Indicators", None))
        self.actionObjects.setText(QCoreApplication.translate("MainWindow", u"Objects", None))
        self.actionExperts.setText(QCoreApplication.translate("MainWindow", u"Experts", None))
        self.actionScripts.setText(QCoreApplication.translate("MainWindow", u"Scripts", None))
        self.actionDepth_of_Market.setText(QCoreApplication.translate("MainWindow", u"Depth of Market", None))
        self.actionIndicators_List.setText(QCoreApplication.translate("MainWindow", u"Indicators List", None))
        self.actionObjects_2.setText(QCoreApplication.translate("MainWindow", u"Objects", None))
        self.actionExperts_List.setText(QCoreApplication.translate("MainWindow", u"Experts List", None))
        self.actionBar_Chart_2.setText(QCoreApplication.translate("MainWindow", u"Bar Chart", None))
        self.actionCandle_Stick.setText(QCoreApplication.translate("MainWindow", u"Candle Stick", None))
        self.actionLine_Chart_2.setText(QCoreApplication.translate("MainWindow", u"Line Chart", None))
        self.actionTime_Frames_2.setText(QCoreApplication.translate("MainWindow", u"Time Frames", None))
        self.actionTemplates.setText(QCoreApplication.translate("MainWindow", u"Templates", None))
        self.actionGrid.setText(QCoreApplication.translate("MainWindow", u"Grid", None))
        self.actionAuto_Scroll.setText(QCoreApplication.translate("MainWindow", u"Auto Scroll", None))
        self.actionCharts_shift.setText(QCoreApplication.translate("MainWindow", u"Charts shift", None))
        self.actionVolumes.setText(QCoreApplication.translate("MainWindow", u"Volumes", None))
        self.actionTick_Volumes.setText(QCoreApplication.translate("MainWindow", u"Tick Volumes", None))
        self.actionTrade_Levels.setText(QCoreApplication.translate("MainWindow", u"Trade Levels", None))
        self.actionTrade_History.setText(QCoreApplication.translate("MainWindow", u"Trade History", None))
        self.actionZomm_In.setText(QCoreApplication.translate("MainWindow", u"Zomm In", None))
        self.actionZoom_out.setText(QCoreApplication.translate("MainWindow", u"Zoom out", None))
        self.actionstep_by_step.setText(QCoreApplication.translate("MainWindow", u"step by step", None))
        self.actionProperties.setText(QCoreApplication.translate("MainWindow", u"Properties", None))
        self.actionNew_Order_2.setText(QCoreApplication.translate("MainWindow", u"New Order", None))
        self.actionStratergy_Tester_Agents_management.setText(QCoreApplication.translate("MainWindow", u"Stratergy Tester Agents Manager", None))
        self.actionMetaQuote_Language_Editor.setText(QCoreApplication.translate("MainWindow", u"MetaQuote Language Editor", None))
        self.actionTask_Manager.setText(QCoreApplication.translate("MainWindow", u"Task Manager", None))
        self.actionGlobal_Variables.setText(QCoreApplication.translate("MainWindow", u"Global Variables", None))
        self.actionMQL5_market.setText(QCoreApplication.translate("MainWindow", u"MQL5 Market", None))
        self.actionMQL5_signals.setText(QCoreApplication.translate("MainWindow", u"MQL5 Signals", None))
        self.actionMQL5_Virtual_Hosting.setText(QCoreApplication.translate("MainWindow", u"MQL5 Virtual Hosting", None))
        self.actionOptions.setText(QCoreApplication.translate("MainWindow", u"Options", None))
        self.actionTile_Windows.setText(QCoreApplication.translate("MainWindow", u"Tile Windows", None))
        self.actionCascade.setText(QCoreApplication.translate("MainWindow", u"Cascade", None))
        self.actionTile_Horizantally.setText(QCoreApplication.translate("MainWindow", u"Tile Horizantally", None))
        self.actionTile_Verically.setText(QCoreApplication.translate("MainWindow", u"Tile Verically", None))
        self.actionArrange_Icons.setText(QCoreApplication.translate("MainWindow", u"Arrange Icons", None))
        self.actionReset_to_Default.setText(QCoreApplication.translate("MainWindow", u"Reset to Default", None))
        self.actionResolution.setText(QCoreApplication.translate("MainWindow", u"Resolution", None))
        self.actionHelp_Topic_s.setText(QCoreApplication.translate("MainWindow", u"Help Topic's", None))
        self.actionWhat_s_New.setText(QCoreApplication.translate("MainWindow", u"What's New", None))
        self.actionMQL5_Telegram_channel.setText(QCoreApplication.translate("MainWindow", u"MQL5 Telegram channel", None))
        self.actionVideo_Guides.setText(QCoreApplication.translate("MainWindow", u"Video Guides", None))
        self.actionMQL5_Webtrader.setText(QCoreApplication.translate("MainWindow", u"MQL5 Webtrader", None))
        self.actionMQL5_Docummentation.setText(QCoreApplication.translate("MainWindow", u"MQL5 Docummentation", None))
        self.actiontheme.setText(QCoreApplication.translate("MainWindow", u"theme", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuNew_Chart.setTitle(QCoreApplication.translate("MainWindow", u"New Chart", None))
        self.menuForex.setTitle(QCoreApplication.translate("MainWindow", u"Forex", None))
        self.menuIndexes.setTitle(QCoreApplication.translate("MainWindow", u"Indexes", None))
        self.menuNasdaq.setTitle(QCoreApplication.translate("MainWindow", u"Nasdaq", None))
        self.menuStock.setTitle(QCoreApplication.translate("MainWindow", u"Stock", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuColors.setTitle(QCoreApplication.translate("MainWindow", u"Colors", None))
        self.menuToolbars.setTitle(QCoreApplication.translate("MainWindow", u"Toolbars", None))
        self.menuLanguages.setTitle(QCoreApplication.translate("MainWindow", u"Languages", None))
        self.menuInsert.setTitle(QCoreApplication.translate("MainWindow", u"Insert", None))
        self.menuCharts.setTitle(QCoreApplication.translate("MainWindow", u"Charts", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuWindows.setTitle(QCoreApplication.translate("MainWindow", u"Windows", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

