"""
theme_applier.py  –  Generates QSS stylesheets from token dicts and
applies them to QWidget targets.

Usage:
    from Theme.theme_applier import ThemeApplier
    ThemeApplier.apply(my_widget, tokens)

All colour values come exclusively from the token dict – no hardcoded
hex values live here.
"""
from __future__ import annotations
from typing import Dict


def _qss(tokens: Dict[str, str]) -> str:
    t = tokens
    return f"""
/* ============================================================
   JetFyx Application Stylesheet – generated by ThemeApplier
   ============================================================ */

/* ---- Root / Window ---- */
QMainWindow, QWidget {{
    background-color: {t['bg_window']};
    color: {t['text_primary']};
    font-family: "Segoe UI", "Inter", "Arial", sans-serif;
    font-size: 12px;
}}

/* ---- Dock widgets ---- */
QDockWidget {{
    background: {t['bg_panel']};
    color: {t['text_primary']};
    border: none;
}}
QDockWidget::title {{
    background: {t['bg_header']};
    color: {t['text_secondary']};
    padding: 4px 8px;
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
}}

/* ---- Menu bar ---- */
QMenuBar {{
    background: {t['bg_header']};
    color: {t['text_primary']};
    border-bottom: 1px solid {t['border_separator']};
}}
QMenuBar::item:selected {{
    background: {t['bg_button_hover']};
    color: {t['text_primary']};
}}
QMenu {{
    background: {t['bg_popup']};
    color: {t['text_primary']};
    border: 1px solid {t['border_primary']};
    border-radius: 6px;
}}
QMenu::item:selected {{
    background: {t['accent']};
    color: {t['accent_text']};
}}

/* ---- Toolbar ---- */
QToolBar {{
    background: {t['bg_header']};
    border-bottom: 1px solid {t['border_separator']};
    spacing: 4px;
    padding: 2px;
}}

/* ---- Status bar ---- */
QStatusBar {{
    background: {t['bg_header']};
    color: {t['text_secondary']};
    border-top: 1px solid {t['border_separator']};
}}

/* ---- Tab bar ---- */
QTabBar {{
    background: transparent;
}}
QTabBar::tab {{
    background: {t['bg_tab_inactive']};
    color: {t['text_tab_inactive']};
    border: none;
    border-bottom: 3px solid transparent;
    padding: 7px 16px;
    margin-right: 2px;
    font-weight: 600;
    font-size: 12px;
}}
QTabBar::tab:selected {{
    background: {t['bg_tab_active']};
    color: {t['text_tab_active']};
    border-bottom: 3px solid {t['accent']};
}}
QTabBar::tab:hover {{
    background: {t['bg_button_hover']};
    color: {t['text_primary']};
}}

/* ---- Table views ---- */
QTableView, QTreeView {{
    background: {t['bg_widget']};
    alternate-background-color: {t['bg_row_alt']};
    color: {t['text_primary']};
    gridline-color: {t['border_separator']};
    border: none;
    selection-background-color: {t['bg_selected']};
    selection-color: {t['text_selected']};
}}
QTableView::item:hover, QTreeView::item:hover {{
    background: {t['bg_row_hover']};
}}
QTableView::item:selected, QTreeView::item:selected {{
    background: {t['bg_selected']};
    color: {t['text_selected']};
}}
QHeaderView::section {{
    background: {t['bg_header']};
    color: {t['text_header']};
    border: none;
    border-right: 1px solid {t['border_separator']};
    border-bottom: 1px solid {t['border_separator']};
    padding: 4px 8px;
    font-weight: 600;
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.3px;
}}

/* ---- Input fields ---- */
QLineEdit, QTextEdit, QPlainTextEdit, QSpinBox, QDoubleSpinBox, QComboBox {{
    background: {t['bg_input']};
    color: {t['text_primary']};
    border: 1px solid {t['border_primary']};
    border-radius: 5px;
    padding: 5px 8px;
    selection-background-color: {t['accent']};
}}
QLineEdit:focus, QTextEdit:focus, QPlainTextEdit:focus,
QSpinBox:focus, QDoubleSpinBox:focus {{
    border-color: {t['border_focus']};
}}
QComboBox::drop-down {{
    border: none;
    width: 20px;
}}
QComboBox QAbstractItemView {{
    background: {t['bg_popup']};
    color: {t['text_primary']};
    border: 1px solid {t['border_primary']};
    selection-background-color: {t['accent']};
    selection-color: {t['accent_text']};
}}

/* ---- Buttons ---- */
QPushButton {{
    background: {t['bg_button']};
    color: {t['text_primary']};
    border: 1px solid {t['border_primary']};
    border-radius: 5px;
    padding: 5px 14px;
    font-weight: 500;
}}
QPushButton:hover {{
    background: {t['bg_button_hover']};
    border-color: {t['border_focus']};
}}
QPushButton:pressed {{
    background: {t['accent']};
    color: {t['accent_text']};
    border-color: {t['accent']};
}}
QPushButton:flat, QPushButton[flat="true"] {{
    background: transparent;
    border: none;
}}

/* ---- Scrollbars ---- */
QScrollBar:vertical {{
    background: {t['scrollbar_bg']};
    width: 8px;
    border-radius: 4px;
}}
QScrollBar::handle:vertical {{
    background: {t['scrollbar_handle']};
    border-radius: 4px;
    min-height: 30px;
}}
QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {{
    height: 0;
}}
QScrollBar:horizontal {{
    background: {t['scrollbar_bg']};
    height: 8px;
    border-radius: 4px;
}}
QScrollBar::handle:horizontal {{
    background: {t['scrollbar_handle']};
    border-radius: 4px;
    min-width: 30px;
}}
QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {{
    width: 0;
}}

/* ---- Dialogs ---- */
QDialog {{
    background: {t['bg_popup']};
    color: {t['text_primary']};
    border-radius: {t['popup_border_radius']};
}}

/* ---- Labels ---- */
QLabel {{
    color: {t['text_primary']};
    background: transparent;
}}

/* ---- Separators ---- */
QFrame[frameShape="4"],
QFrame[frameShape="5"] {{
    color: {t['border_separator']};
}}

/* ---- Bottom bar ---- */
QWidget#orders_bottom_bar {{
    background: {t['bg_bottom_bar']};
    border-top: 1px solid {t['border_separator']};
}}

/* ---- Orders widget ---- */
QWidget#OrdersWidget {{
    background: {t['bg_widget']};
}}
QTabBar#OrdersTabBar::tab {{
    background: {t['bg_tab_inactive']};
    color: {t['text_tab_inactive']};
    border: none;
    border-bottom: 3px solid transparent;
    padding: 8px 16px;
    font-weight: 600;
    font-size: 12px;
}}
QTabBar#OrdersTabBar::tab:selected {{
    background: {t['bg_tab_active']};
    color: {t['text_tab_active']};
    border-bottom: 3px solid {t['accent']};
}}
QTabBar#OrdersTabBar::tab:hover {{
    background: {t['bg_button_hover']};
}}

/* ---- Settings buttons ---- */
QPushButton#OrdersSettingsBtn, QPushButton#OrdersFunnelBtn {{
    background: transparent;
    border: none;
    color: {t['text_primary']};
    font-size: 16px;
    font-family: "Segoe UI Symbol", "Segoe UI", sans-serif;
    padding: 0px;
}}
QPushButton#OrdersSettingsBtn:hover, QPushButton#OrdersFunnelBtn:hover {{
    background: {t['bg_button_hover']};
    border-radius: 4px;
}}

/* ---- Positive / Negative values ---- */
QLabel[role="positive"] {{ color: {t['text_positive']}; }}
QLabel[role="negative"] {{ color: {t['text_negative']}; }}
"""


class ThemeApplier:
    """Static helper.  Apply a token dict as a QSS stylesheet to a widget."""

    @staticmethod
    def apply(widget, tokens: Dict[str, str]):
        """Set global stylesheet on *widget* (usually the QApplication or root widget)."""
        try:
            widget.setStyleSheet(_qss(tokens))
        except Exception as exc:
            import logging
            logging.getLogger(__name__).exception("ThemeApplier.apply failed: %s", exc)

    @staticmethod
    def apply_to_app(tokens: Dict[str, str]):
        """Apply the stylesheet to the running QApplication instance."""
        try:
            from PySide6.QtWidgets import QApplication
            app = QApplication.instance()
            if app:
                app.setStyleSheet(_qss(tokens))
        except Exception as exc:
            import logging
            logging.getLogger(__name__).exception("ThemeApplier.apply_to_app failed: %s", exc)

    @staticmethod
    def table_qss(tokens: Dict[str, str]) -> str:
        """Return a scoped QSS string for tables/headers only."""
        t = tokens
        return (
            f"QTableView::item:hover {{ background: {t['bg_row_hover']}; }}"
            f"QTableView::item:selected {{ background: {t['bg_selected']}; color: {t['text_selected']}; }}"
            f"QTableView {{ selection-background-color: {t['bg_selected']}; selection-color: {t['text_selected']}; }}"
        )

    @staticmethod
    def bottom_bar_qss(tokens: Dict[str, str]) -> str:
        t = tokens
        return (
            f"background: {t['bg_bottom_bar']}; "
            f"border-top: 1px solid {t['border_separator']};"
        )